const ioControlConfig = {
    'outLight':[
        [
            [
                {
                    'title':'远光灯',
                    'data':[
                        [
                            {
                                'key':'左远光灯',
                                'value':'leftHighBeam'
                            },
                            {
                                'key':'右远光灯',
                                'value':'rightHighBeam'
                            }
                        ]
                    ]
                },
                {
                    'title':'近光灯',
                    'data':[
                        [
                            {
                                'key':'左近光灯',
                                'value':'fullLight'
                            },
                            {
                                'key':'右近光灯',
                                'value':'rightDippedHeadlight'
                            }
                        ]
                    ]
                },
                {
                    'title':'转向灯',
                    'data':[
                        [
                            {
                                'key':'左转向灯',
                                'value':'leftTurnSignal'
                            },
                            {
                                'key':'右转向灯',
                                'value':'rightTurnSignal'
                            }
                        ]
                    ]
                }
            ],
            [
                {
                    'title':'倒车灯',
                    'data':[
                        [
                            {
                                'key':'左倒车灯',
                                'value':'leftBackLight'
                            },
                            {
                                'key':'右倒车灯',
                                'value':'rightBackLight'
                            }
                        ]
                    ]
                },
                {
                    'title':'日行灯',
                    'data':[
                        [
                            {
                                'key':'左日行灯',
                                'value':'leftLineOfLamp'
                            },
                            {
                                'key':'右日行灯',
                                'value':'rightLineOfLamp'
                            }
                        ]
                    ]
                },
                {
                    'title':'logo灯',
                    'data':[
                        [
                            {
                                'key':'左logo灯',
                                'value':'leftLogoLights'
                            },
                            {
                                'key':'右logo灯',
                                'value':'rightLogoLights'
                            }
                        ]
                    ]
                }
            ],
            [
                {
                    'title':'雾灯',
                    'data':[
                        [
                            {
                                'key':'左前雾灯',
                                'value':'leftFrontFogLamps'
                            },
                            {
                                'key':'右前雾灯',
                                'value':'rightFrontFogLamps'
                            }
                        ],
                        [
                            {
                                'key':'左后雾灯',
                                'value':'leftRearFogLamps'
                            },
                            {
                                'key':'右后雾灯',
                                'value':'rightRearFogLamps'
                            }
                        ]
                    ]
                },
                {
                    'title':'示廓灯',
                    'data':[
                        [
                            {
                                'key':'左位置灯',
                                'value':'leftLight'
                            },
                            {
                                'key':'右位置灯',
                                'value':'rightLight'
                            }
                        ],
                        [
                            {
                                'key':'后中位置灯',
                                'value':'rearCenterPositionLight'
                            }
                        ]
                    ]
                },
                {
                    'title':'制动灯',
                    'data':[
                        [
                            {
                                'key':'低位制动灯',
                                'value':'lowStopLamp'
                            },
                            {
                                'key':'高位制动灯',
                                'value':'highStopLamp'
                            }
                        ]
                    ]
                }
            ]
        ],
        [
            {
                'key':'牌照灯',
                'value':'licensePlateLamp'
            },
            {
                'key':'开关背景光',
                'value':'switchingBackgroundLight'
            },
            {
                'key':'ADB唤醒',
                'value':'ADBAwaken'
            }
        ]
    ],
    'inLight':[
        [
            {
                'key':'内灯',
                'value':'inTheLight'
            },
            {
                'key':'危险报警灯',
                'value':'hazardAlarmLamp'
            }
        ],
        [
            {
                'key':'节电指示灯',
                'value':'powerSavingIndicatorLight'
            },
            {
                'key':'儿童锁指示灯',
                'value':'childLockIndicatorLight'
            }
        ],
        [
            {
                'key':'中控锁指示灯',
                'value':'centerLockIndicatorLight'
            },
            {
                'key':'一键启动按钮指示灯',
                'value':'buttonIndicator'
            }
        ]
    ],
    'other':[
        [
            {
                'key':'后雨刮',
                'value':'reaWiper'
            },
            {
                'key':'后除霜',
                'value':'PostDefrost'
            }
        ],
        [
            {
                'key':'前洗涤',
                'value':'preWashing'
            },
            {
                'key':'后洗涤',
                'value':'afterWashing'
            }
        ],
        [
            {
                'key':'后视镜折叠',
                'value':'mirrorFold'
            },
            {
                'key':'后视镜展开',
                'value':'rearviewMirrorDeployment'
            }
        ],
        [
            {
                'key':'后备箱解锁',
                'value':'trunkUnlocking'
            }
        ]
    ]
}
const ioFieldList=[
    [
        'leftTurnSignal',
        'rightTurnSignal',
        'leftLight',
        'rightLight',
        'rearCenterPositionLight',
        'fullLight',
        'rightDippedHeadlight',
        'ADBAwaken',
        'leftHighBeam',
        'rightHighBeam',
        'leftRearFogLamps',
        'rightRearFogLamps',
        'leftFrontFogLamps',
        'rightFrontFogLamps',
        'lowStopLamp',
        'highStopLamp',
        'leftLineOfLamp',
        'rightLineOfLamp',
        'leftLogoLights',
        'rightLogoLights',
        'leftBackLight',
        'rightBackLight',
        'licensePlateLamp',
        'switchingBackgroundLight'
    ],
    [
        'powerSavingIndicatorLight',
        'inTheLight',
        'centerLockIndicatorLight',
        'childLockIndicatorLight',
        'buttonIndicator',
        'hazardAlarmLamp'
    ],
    [
        'reaWiper',
        'preWashing',
        'afterWashing',
        'PostDefrost',
        'trunkUnlocking',
        'mirrorFold',
        'rearviewMirrorDeployment'
    ]
]
export {
    ioControlConfig,
    ioFieldList
} 